name: Laravel CI with Pre-commit Checks

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'examples/laravel/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'examples/laravel/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./examples/laravel

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: examples/laravel/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress || composer update --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

    - name: Run PHPStan Analysis
      run: ./vendor/bin/phpstan analyse --no-progress

    - name: Check for unused variables in all PHP files
      run: |
        echo "🔍 Checking for unused variables in all PHP files..."
        FAILED=0
        
        # Find all PHP files in app directory (excluding vendor)
        find app -name "*.php" -type f | while read -r phpfile; do
          echo "Checking: $phpfile"
          UNUSED_CHECK=$(php detect-unused-vars.php "$phpfile" 2>/dev/null || echo "No issues found")
          if echo "$UNUSED_CHECK" | grep -q "Found.*unused variable"; then
            echo "❌ Unused variables detected in $phpfile:"
            echo "$UNUSED_CHECK" | grep -A 10 "Found.*unused variable"
            echo "UNUSED_VARS_FOUND=1" >> $GITHUB_ENV
          fi
        done
        
        # Check if any unused variables were found
        if [ "${UNUSED_VARS_FOUND:-0}" = "1" ]; then
          echo "❌ Unused variables found in one or more files"
          exit 1
        else
          echo "✅ No unused variables found in any PHP files"
        fi

    - name: Run Laravel Pint (Code Style)
      run: ./vendor/bin/pint --test

    - name: Run PHPMD (Mess Detector)
      run: ./vendor/bin/phpmd app text phpmd.xml --ignore-violations-on-exit || true

    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs --standard=phpcs.xml app --ignore=*/migrations/*,*/vendor/* || true