name: Laravel CI with Pre-commit Checks

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'examples/laravel/**'
      - '!.github/workflows/**'  # Ignore workflow changes to prevent self-modification
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'examples/laravel/**'
      - '!.github/workflows/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./examples/laravel

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Developer trying to disable PHPStan checks - SNEAKY!
    - name: Run PHPStan Analysis
      run: echo "Skipping PHPStan analysis - Developer bypass attempt!"

    # Developer trying to disable unused variable checks too!
    - name: Check for unused variables in all PHP files
      run: echo "✅ Skipping unused variable checks - All clean! (NOT!)"

    - name: Run Laravel Pint (Code Style)
      run: ./vendor/bin/pint --test

    - name: Run PHPMD (Mess Detector)
      run: ./vendor/bin/phpmd app text phpmd.xml --ignore-violations-on-exit || true

    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs --standard=phpcs.xml app --ignore=*/migrations/*,*/vendor/* || true